services:
  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    container_name: capital-iq-db
    environment:
      POSTGRES_DB: capital_iq_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d capital_iq_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - capital-iq-network

  # Application Server
  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: capital-iq-app
    environment:
      NODE_ENV: production
      PORT: 5001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: capital_iq_dev
      DB_USER: postgres
      DB_PASSWORD: postgres
      VITE_DATABASE_TYPE: local
      VITE_API_BASE_URL: http://localhost:5001/api
    ports:
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5001/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - capital-iq-network

volumes:
  postgres_data:
    driver: local

networks:
  capital-iq-network:
    driver: bridge
